### PR TITLE
Added schema tag to all missing examples

### PR DESCRIPTION
**Pull request by SiddhanthUnnithan**
# PR into Azure/azureml-v2-preview

## Checklist

I have:

- [X] read and followed the contributing guidelines

## Changes

- Added $schema tags where missing in the doc examples

### CODE REVIEW

**Review by mx-iao — APPROVED** [review]

**Comment by SiddhanthUnnithan** [comment]
@rihorn2 can we still merge these changes? The check is failing because of $schema being an unrecognized field for environment create.

**Comment by rihorn2** [comment]
@SiddhanthUnnithan I will get a small PR out to add this.

**Comment by lostmygithubaccount** [comment]
please start using the public preview examples: https://github.com/Azure/azureml-examples/tree/cli-preview

**Comment by rihorn2** [comment]
@SiddhanthUnnithan Please try now, all schema should allow $schema prop

**Pull request closed without merging**
