### PR TITLE
AutoML jobs CLI documentation (PRIVATE PREVIEW)

### PR DESCRIPTION
**Pull request by CESARDELATORRE**
# PR into Azure/azureml-v2-preview

AutoML jobs CLI documentation - PRIVATE PREVIEW.
Note mention to PRIVATE PREVIEW and asking to send email in order to request to be enrolled into PRIVATE PREVIEW. 

## Checklist

I have:

- [X] read and followed the contributing guidelines

## Changes

-

Fixes #

### CODE REVIEW

**Comment by CESARDELATORRE** [comment]
@jpe316 Please, can you do a quick review and merge if it's ok?
The content is not large, so it should be quick. :)

**Comment by lostmygithubaccount** [comment]
the examples added look untested, and I wasn't aware AutoML was ready for private preview - is this working today?

**Comment by CESARDELATORRE** [comment]
@lostmygithubaccount About:
> the examples added look untested, and I wasn't aware AutoML was ready for private preview - is this working today?

**Why do the examples look untested?** 

The examples in the doc are tested by me and working today in CANARY:

https://ml.azure.com/experiments/id/710831da-f25d-4479-af7b-b055a02532a0?wsid=/subscriptions/381b38e9-9840-4719-a5a0-61d9585e1e91/resourceGroups/sasum_centraluseuap_rg/providers/Microsoft.MachineLearningServices/workspaces/sasum_eastus2euap_ws&tid=72f988bf-86f1-41af-91ab-2d7cd011db47

image

AutoML CLI will release as PRIVATE PREVIEW on March 31st. That was the original plan agreed with Sindhura, Daniel and Jordan.

**Comment by lostmygithubaccount** [comment]
they should be tested through github actions like other samples in this repository

**Comment by CESARDELATORRE** [comment]
> they should be tested through github actions like other samples in this repository
@lostmygithubaccount 
Nice, can you implement the GitHub actions for it? or who's implementing those github actions for any example added to the repo?

This is the Dataset file I'm using in the provided example. It needs to be uploaded/registered into the Workspace, in the first place, before running the CLI, as explained in the doc:

https://azmlworkshopdata.blob.core.windows.net/safedriverdata/porto_seguro_safe_driver_prediction_train.csv

With that, the job should run properly.

**Comment by CESARDELATORRE** [comment]
@lostmygithubaccount, Is it possible for you to implement the GitHub actions required for testing these AutoML samples I mentioned above as part of this PR so this AutoML CLI documentation can be merged in, please? :)

This content is in the following branch, so you should be able to update it, I believe:
Branch: cesardl/automl-cli-doc

**Comment by lostmygithubaccount** [comment]
@CESARDELATORRE this PR is out of date, please see latest contributing guidelines for migrating the AutoML private preview to this repo

**Pull request closed without merging**
